name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
     - uses: actions/checkout@v2

     - run: ci/build-app.sh

     - uses: actions/upload-artifact@v2
       with:
         name: build
         path: app.jar

  test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [build]
    steps:
     - uses: actions/download-artifact@v2
       with:
         name: build
         path: app.jar

     - run: ci/unit-test-app.sh
