name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
     - uses: actions/checkout@v2

     - run: ci/build-app.sh

     - uses: actions/upload-artifact@v2
       with:
         name: build
         path: app

  test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [build]
    steps:
     - uses: actions/download-artifact@v2
       with:
         name: build
         path: app

     - run: ci/unit-test-app.sh

  push:
    runs-on: ubuntu-latest
    needs: [build, test]

    env:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_passsword: ${{ secrets.DOCKERHUB_PASSWORD }}
      GIT_COMMIT: $COMMIT_SHA

    steps:
     - uses: docker/login-action@v1.10.0
       name: Login to Dockerhub
       with:
        - ${{ env.docker_username }}
        - ${{ env.docker_password }}

     - name: Build and push
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: $docker_username/micronaut-app:1.0-${GIT_COMMIT::8} 
