name: hello-world
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_passsword: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
     - uses: actions/checkout@v2

     - run: chmod +x ci/build-app.sh && ci/build-app.sh

     - uses: actions/upload-artifact@v2
       with:
         name: build
         path: .

  test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [build]
    steps:
     - uses: actions/download-artifact@v2
       with:
         name: build
         path: .

     - run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh

  push:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
     - uses: actions/checkout@v2
     - uses: actions/download-artifact@v2
       with:
         name: build
         path: .

     - name: build docker
       run: chmod +x ci/build-docker.sh && ci/build-docker.sh
     - name: push docker
       run: chmod +x ci/push-docker.sh && ci/push-docker.sh
