name: hello-world
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_passsword: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
     - uses: actions/checkout@v2

     - run: ci/build-app.sh

     - uses: actions/upload-artifact@v2
       with:
         name: build
         path: .

  test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [build]
    steps:
     - uses: actions/checkout@v2
     - uses: actions/download-artifact@v2
       with:
         name: build
         path: .

     - run: ci/unit-test-app.sh

  push:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
     - uses: actions/download-artifact@v2
       with:
         name: build
         path: .

     - uses: docker/login-action@v1.10.0
       name: Login to Dockerhub
       with:
         username: ${{ env.docker_username }}
         password: ${{ env.docker_password }}

     - name: Build and push
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: $docker_username/micronaut-app:1.0-${GIT_COMMIT::8} 
